name: Sahibpreet Kaur
permalink: :year/:month/:day/:title
baseurl: /sahib-daily-diary

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2021
now: 2023
 
# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : sahibkaur81@gmail.com
  github : sahibkaur
  twitter : sahibbkaur

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   Diary: "/diary"

   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed